version: '3.4'

services:

  gateway:
    image: nginx:1.27.1-alpine
    container_name: gateway
    entrypoint: sh -c
      "envsubst '$$DEPLOY_HOST' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
      nginx -g 'daemon off;'"
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      HOST: ${HOST}
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./nginx/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 256M

  market-basket-analysis-api:
    image: kronmag/market-basket-analysis-api
    container_name: market-basket-analysis-api
    volumes:
      - market-basket-analysis-data:/app/data
    restart: on-failure
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:8080"]
      timeout: 10s
      interval: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M

volumes:
  market-basket-analysis-data: