version: '3.4'

services:

  market-basket-analysis-api:
    image: market-basket-analysis-api
    build:
      context: .
      dockerfile: MarketBasketAnalysis.Server.API/Dockerfile
    container_name: market-basket-analysis-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8080:8080
    volumes:
      - market-basket-analysis-data:/app/data
    restart: on-failure
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:8080"]
      timeout: 10s
      interval: 5s
      retries: 10
      start_period: 30s

  grpc-ui:
    image: fullstorydev/grpcui:v1.4.1
    command: -plaintext market-basket-analysis-api:8080
    restart: on-failure
    ports:
      - 8082:8080
    depends_on:
      market-basket-analysis-api:
        condition: service_started

volumes:
  market-basket-analysis-data: